serviceName: "spec"
deploymentName: "spec"
replicas: 1
command: "bin/entry bundle exec rails s -p 3005 -b 0.0.0.0"
image:
  repository: "registry.cn-shenzhen.aliyuncs.com/yolanda/spec:sit-1"
  pullPolicy: "IfNotPresent"
  pullSecrets: ""
service:
  export: true
  type: "ClusterIP"
  probeScheme: "HTTPS"
  # port: 0
  # targetPort: 9000
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1000Mi
labels:
  app: "spec"
envs: 

# configMapMounts:
#   - XXX: XXX
grpcProxy: false

ingress:
  enabled: false
  certManager: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - name: xxx
    path: /
    tls: false
    tlsSecret: xxx
  secrets: