serviceName: "spec-test3"
deploymentName: "spec1-test3"
replicas: 1
command: "bin/entry bundle exec rails s -p 3005 -b 0.0.0.0"
image:
  repository: "registry.cn-shenzhen.aliyuncs.com/yolanda/spec:sit-1"
  pullPolicy: "IfNotPresent"
  pullSecrets: ""
service:
  export: true
  type: ClusterIP
  probeScheme: "HTTPS"
  ports:
    http: 9001
  targetPort: 9000
  # targetPort: 9000
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1000Mi
labels:
  app: "spec-test3"
envs: 
  xxx: "xxx"
# configMapMounts:
#   - XXX: XXX
grpcProxy: false

ingress:
  enabled: false
  host: xxx
  backend: xxx
  backendPort: 3005
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    tls: false
    tlsSecret: xxx
  secrets: