apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.serviceName }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Values.ingress.backend }}"
          servicePort: {{ .Values.ingress.backendPort }}