apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deploymentName }}"
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  replicas: {{ default 1 .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: "{{ $val }}"
        {{- end }}
    spec:
      containers:
        - name: "{{ .Values.deploymentName }}"
          image: "{{.Values.image.repository}}"
          lifecycle:
            preStop:
              exec:
                command:
                - sleep
                - 20s
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          env:
            {{- range $key, $val := .Values.envs }}
            - name: "{{ $key }}"
              value: "{{ $val }}"
            {{- end }}
          resources:
            requests:
              cpu: "{{.Values.resources.requests.cpu}}"
              memory: "{{.Values.resources.requests.memory}}"
            limits:
              cpu: "{{.Values.resources.limits.cpu}}"
              memory: "{{.Values.resources.limits.memory}}"
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range $key, $val := .Values.image.pullSecrets }}
        - name: "{{ $val }}"
        {{- end }}
      {{- end }}
