apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
  labels:
    app: "{{ .Values.serviceName }}"
spec:
  ports:
  - name: "http-9000"
    port: 9000
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: "{{ .Values.serviceName }}"
  type: ClusterIP
