{{- if .Values.inner-ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.serviceName }}"
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: "{{ .Values.inner-ingress.host }}"
    http:
      paths:
      - path: /{{ .Values.serviceName }}
        backend:
          serviceName: "{{ .Values.inner-ingress.backend }}"
          servicePort: 10000
{{- end -}}