serviceName: "spec-test3"
deploymentName: "spec1-test3"
replicas: 1
command: ["bin/entry"]
image:
  repository: "registry.cn-shenzhen.aliyuncs.com/yolanda/spec:sit-1"
  pullPolicy: "IfNotPresent"
  pullSecrets: ""
service:
  export: true
  type: ClusterIP
  probeScheme: "HTTPS"
  ports:
    http: 9001
  targetPort: 9000
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 2048Mi
labels:
  app: "spec-test3"
envs: 
  xxx: "xxx"
# configMapMounts:
#   - XXX: XXX
grpcProxy: false

ingress:
  enabled: false
  host: xxx
  backend: xxx
  backendPort: 3005
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    tls: false
    tlsSecret: xxx
  secrets:

iningress:
  enabled: false
  host: gateway-inner.yolanda.hk
  path: /yoga-web
  backend: yoga-web
  backendPort: 10000
  annotations: 
    kubernetes.io/ingress.class: kong

crons:
  "0":
    name: my-first-cron
    repository: nginx    
    command: my:first:cron
    schedule: "*/10 * * * *"
  "1":
    name: my-second-cron
    command: my:second:cron
    repository: nginx
    schedule: "*/3 * * * *"